version: "3.11"

services:
  redis:
    image: redis
    restart: always


  webapp:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  worker:
      restart: always
      build:
        context: .
      volumes:
        - ./cats:/webapp/cats
      command: ['celery', '--workdir=.', '-A', 'config', 'worker']
